version: '3'

services:
  devops01:
    build:
      dockerfile: ../dockerfile
      context: .
      args:
        VAR_PROFILE: dev
    environment:
      - HOST=10.125.64.99
      - PORT=33061
      - USER=root
      - PASSWORD=root
    expose:
      - "8092"
    ports:
      -  "8092:8090"